### PR TITLE
add before_after_ai2html template

### PR DESCRIPTION
**Pull request by DanielJWood**
Hiya, I created a template out of the Before and After template combined with an ai2html template. I can see this being extremely useful any time we have before and after images, since often it might help to have annotations on whatever is changing from image to image. See this [example](https://www.npr.org/2023/10/06/1203372829/the-bruising-artillery-battle-in-ukraine-has-left-a-scar-that-is-visible-from-sp).

Limitations...previously, the two images would be referenced in the google sheets. In this case, those two images are present inside illustrator instead. Thus, set up is a bit more manual, and you have to be sure that you have them lined up correctly in the .ai file. 

Otherwise, you have the full capability of illustrator/ai2html at your disposal. 

If you like this we can merge as is, or I can simplify/clean up the .ai file to be more general.

### CODE REVIEW

**Comment by alykat** [comment]
2 things that stood out to me when I gave this an initial look:

* I get an error about missing linked files when I open the AI file. Possible to fix that? Maybe replace the base image with just solid blocks of color for example purposes.
* The AI file is stored in a `synced` folder rather than `assets` like the other 2 ai2html templates. Given how weighty these files can get, working within `synced` probably a best practice, but it does mean that the AI file will be gitignored and it's not totally obvious that this is how it works. Is there a good way to signal this clearly to users? (Maybe in the readme AND the ai2html file?) Should we update the other 2 ai2html templates accordingly?

**Comment by DanielJWood** [comment]
@alykat when you have a second, let's huddle about what you're thinking abut that second point. Not sure what the best path forward is. I realize that this `synced` is committed to github while it won't be in graphics-js. Is that okay?

**Comment by DanielJWood** [comment]
@alykat, a reminder about this...I recently used this for the Domicide piece without any issue.

**Comment by DanielJWood** [comment]
@alykat I could always tag someone else to kick the tires if that'd be helpful to offload from you! I just added the new fonts from master _back into_ this branch so that it stays up to date with master.

**Comment by alykat** [comment]
Looks good.

I added this note to the subhed on the template:

>Friendly reminder: The AI file does not get committed to Github. Run `node cli sync $SLUG` to sync the Illustrator file to S3 separately.

2 small things and then you're free to squash-n-merge:
* Update fonts to match the ai2html map template (since we've moved from Lato to NPR Sans)
* Can you move the ai2html config text block next to the style examples? It's way off the top of the document. And can you set the initial zoom to include all artboards when you first open it?

**Pull request merged**
